# Generated by Django 3.2.11 on 2024-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0002_auto_20240919_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sheshi',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='window',
        ),
        migrations.AlterField(
            model_name='thing',
            name='status',
            field=models.CharField(choices=[('0', 'available'), ('1', 'unavailable')], default='0', max_length=1),
        ),
    ]
