# Generated by Django 3.2.11 on 2024-09-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0003_auto_20240919_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='classification',
        ),
        migrations.AddField(
            model_name='thing',
            name='classification_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification1_thing', to='CSAA.classification'),
        ),
        migrations.AddField(
            model_name='thing',
            name='classification_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification2_thing', to='CSAA.classification'),
        ),
    ]
