# Generated by Django 3.2.11 on 2024-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0004_auto_20240919_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
