# Generated by Django 3.2.11 on 2024-09-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0005_thing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='classification_1',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='classification_2',
        ),
        migrations.AddField(
            model_name='thing',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_thing', to='CSAA.classification'),
        ),
    ]
