# Generated by Django 3.2.11 on 2024-09-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0006_auto_20240920_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='tag',
            field=models.ManyToManyField(blank=True, to='CSAA.Tag'),
        ),
    ]
