# Generated by Django 3.2.11 on 2024-09-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0007_thing_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
