# Generated by Django 3.2.11 on 2024-09-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0008_auto_20240920_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='day',
            new_name='weekday',
        ),
    ]
