# Generated by Django 3.2.11 on 2024-09-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0009_rename_day_thing_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='weekday',
            new_name='day',
        ),
    ]
