# Generated by Django 3.2.11 on 2024-09-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0010_rename_weekday_thing_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_child', to='CSAA.user')),
            ],
            options={
                'db_table': 'b_child',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='thing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing_order', to='CSAA.thing'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lesson', to='CSAA.child')),
                ('thing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing_lesson', to='CSAA.thing')),
            ],
            options={
                'db_table': 'b_lesson',
            },
        ),
    ]
