# Generated by Django 3.2.11 on 2024-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0011_auto_20240925_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
