# Generated by Django 3.2.11 on 2024-09-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0012_tag_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='time',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
