# Generated by Django 3.2.11 on 2024-09-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0013_alter_thing_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_time',
            },
        ),
        migrations.RemoveField(
            model_name='thing',
            name='time',
        ),
        migrations.AddField(
            model_name='thing',
            name='time',
            field=models.ManyToManyField(blank=True, to='CSAA.Time'),
        ),
    ]
