# Generated by Django 3.2.11 on 2024-09-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0014_auto_20240928_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='time',
        ),
        migrations.AddField(
            model_name='thing',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_time', to='CSAA.time'),
        ),
    ]
