# Generated by Django 3.2.11 on 2024-10-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0015_auto_20240930_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
