# Generated by Django 3.2.11 on 2024-10-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0016_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
