# Generated by Django 3.2.11 on 2024-10-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0017_alter_thing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
