# Generated by Django 3.2.11 on 2024-10-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0018_alter_thing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
