# Generated by Django 3.2.11 on 2024-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0019_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expect_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_term',
            },
        ),
    ]
