# Generated by Django 3.2.11 on 2024-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0020_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='expect_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='return_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
