# Generated by Django 3.2.11 on 2024-10-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0021_auto_20241009_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='expect_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
