# Generated by Django 3.2.11 on 2024-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0022_auto_20241009_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
