# Generated by Django 3.2.11 on 2024-10-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0023_term_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_order', to='CSAA.child'),
        ),
    ]
