# Generated by Django 3.2.11 on 2024-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0024_auto_20241014_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(default='jack', max_length=30),
            preserve_default=False,
        ),
    ]
