# Generated by Django 3.2.11 on 2024-10-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0025_alter_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_order', to='CSAA.term'),
        ),
    ]
