# Generated by Django 3.2.11 on 2024-10-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0026_order_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
