# Generated by Django 3.2.11 on 2024-10-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0027_auto_20241015_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
