# Generated by Django 3.2.11 on 2024-10-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0029_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='tag',
        ),
        migrations.AddField(
            model_name='thing',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_thing', to='CSAA.tag'),
        ),
    ]
