# Generated by Django 3.2.11 on 2024-10-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0030_auto_20241023_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='leave_students',
            field=models.ManyToManyField(blank=True, related_name='leave_lesson', to='CSAA.Child'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reschedule_students',
            field=models.ManyToManyField(blank=True, related_name='reschedule_lesson', to='CSAA.Child'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_lesson', to='CSAA.Child'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='try_students',
            field=models.ManyToManyField(blank=True, related_name='try_lesson', to='CSAA.Child'),
        ),
    ]
