# Generated by Django 3.2.11 on 2026-09-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0055_dailystudentadjustment_target_lesson_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCoursePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, to='CSAA.Course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSAA.tag')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSAA.term')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CSAA.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roomcoursepermission',
            constraint=models.UniqueConstraint(fields=('room', 'term'), name='unique_room_course_term'),
        ),
    ]
