# Generated by Django 3.2.11 on 2026-09-18 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSAA', '0056_auto_20260916_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTrialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('session_index', models.PositiveSmallIntegerField()),
                ('session_date', models.DateField(db_index=True)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('canceled_time', models.DateTimeField(blank=True, null=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_trial_sessions', to='CSAA.user')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trial_sessions', to='CSAA.user')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_trial_sessions', to='CSAA.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_trial_sessions', to='CSAA.child')),
            ],
            options={
                'db_table': 'b_admin_trial_session',
            },
        ),
        migrations.AddConstraint(
            model_name='admintrialsession',
            constraint=models.UniqueConstraint(fields=('package_key', 'session_index'), name='unique_admin_trial_package_session'),
        ),
    ]
